source :rubygems
gem 'sinatra'
gem 'sinatra-assetpack'
gem 'sinatra-contrib'
gem 'activerecord'
gem 'activerecord-postgresql-adapter'
gem 'sinatra-backbone', :require => 'sinatra/backbone'
gem 'koala'
gem 'sprockets'
gem 'ejs'
gem 'jasmine'
gem 'paperclip'
gem 'fog'
gem 'excon'
